#SUBCONSULTA PARA MOSTRAR AS CONTAS VINCULADAS AOS 
#CLIENTES QUE INFORMARAM O TELEFONE NO CADASTRO

SELECT * FROM contasvinculadas AS cv
WHERE cv.CLIENTE_idCLIENTE GROUP BY cv.CLIENTE_idCLIENTE IN 
(SELECT idCliente FROM cliente WHERE telefone IS NOT NULL);
